services:
  backend:
    build: ./Job_timer
    container_name: back_end
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network

  frontend:
    build: ./Job_Time_Front
    container_name: front_end
    ports:
      - "3000:80"
    networks:
      - network

  db:
    image: postgres:17
    env_file:
      - ./Job_Timer/.env
    container_name: postgres_data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 7792
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
