# Generated by Django 6.0.6 on 2026-07-05 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_bar', models.IntegerField(default=0)),
                ('progress', models.DateTimeField(default=datetime.datetime)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
