# Generated by Django 6.0.6 on 2026-07-05 17:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='date',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='progress',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
