# Generated by Django 6.0.6 on 2026-07-05 17:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_worksession_date_alter_worksession_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='date',
            field=models.DurationField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='progress',
            field=models.DateTimeField(default=datetime.timedelta(0)),
        ),
    ]
